const db = require("../db")

//create a model from a schema
//a schema is a layout of what you want your documents to look like

const Song = db.model("Song",{
    //_id is not required and autogenerated
    title: {type: String, required: true},
    artist: String,
    popularity: {type: Number, min:1, max:10},
    releaseDate: {type: Date, default: Date.now},
    //we can also use arrays in mongoose to define multiple pieces of data
    genre: [String]

})

module.exports = Song